name: Lint code & compile test

on:
  workflow_call:
    inputs:
      RUNNER:
        description: "Runner to use"
        type: string
        required: false
        default: 'ubuntu-latest'
      SKIP_LINT:
        description: "Skip lint step"
        type: boolean
        required: false
        default: false

permissions:
  contents: read
  packages: read

jobs:
  build:
    runs-on: ${{ inputs.RUNNER }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6

      - name: Setup Bun
        uses: oven-sh/setup-bun@3d267786b128fe76c2f16a390aa2448b815359f3 # v2

      - name: Login to GitHub Packages (bun)
        run:
          echo "//npm.pkg.github.com/:_authToken=${GITHUB_TOKEN}" >> .npmrc
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Installing dependencies (bun)
        env:
          NPM_CONFIG_USERCONFIG: .npmrc
        run: bun install --frozen-lockfile

      - name: Lint code (bun)
        if: ${{ inputs.SKIP_LINT != true }}
        run: bun run lint

      - name: Build Code (bun)
        run: bun run build
