name: Lint code & compile test

on:
  workflow_call:
    inputs:
      RUNNER:
        description: "Runner to use"
        type: string
        required: false
        default: 'ubuntu-latest'
      SKIP_LINT:
        description: "Skip lint step"
        type: boolean
        required: false
        default: false
      VERBOSE:
        description: "Enable verbose output for installation"
        type: boolean
        required: false
        default: false
    secrets:
      GH_TOKEN:
        required: false

permissions:
  contents: read
  packages: read

jobs:
  build:
    runs-on: ${{ inputs.RUNNER }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Setup Bun
        uses: oven-sh/setup-bun@3d267786b128fe76c2f16a390aa2448b815359f3 # v2

      - name: Login to GitHub Packages
        run: echo "//npm.pkg.github.com/:_authToken=${GITHUB_TOKEN}" >> .npmrc
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN || secrets.GITHUB_TOKEN }}

      - name: Installing dependencies (bun)
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN || secrets.GITHUB_TOKEN }}
        run: bun install --frozen-lockfile ${{ inputs.VERBOSE && '--verbose' || '' }}

      - name: Lint code (bun)
        if: ${{ inputs.SKIP_LINT != true }}
        run: bun run lint

      - name: Build Code (bun)
        run: bun run build
